# http://travis-ci.org/#!/diyan/pywinrm
language: generic
cache:
  directories:
    - $HOME/.cache/pip
#    - $HOME/.pyenv
matrix:
  include:
    # Python 3.0-3.2 does not support explicit unicode literal, see pep-0414
    # Define 'sudo: false' to run on container-based workers
#    - { os: linux, dist: precise, sudo: false, python: 2.6, env: UBUNTU=12.04 }
#    - { os: linux, dist: precise, sudo: false, python: 2.7, env: UBUNTU=12.04 }
#    - { os: linux, dist: precise, sudo: false, python: 3.3, env: UBUNTU=12.04 }
#    - { os: linux, dist: precise, sudo: false, python: 3.4, env: UBUNTU=12.04 }
#    - { os: linux, dist: precise, sudo: false, python: 3.6-dev, env: UBUNTU=12.04 }
#    - { os: linux, dist: precise, sudo: false, python: 3.5, env: UBUNTU=12.04 }
#    - { os: linux, dist: precise, sudo: false, python: pypy, env: UBUNTU=12.04 }
    # TODO wait for Travis CI update from PyPy3 v2.4.0 to PyPy3.3 v5.5, reason:
    #   cryptography 1.0 is not compatible with PyPy < 2.6
    # python: pypy3

    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=2.6.9 }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=2.7.13 }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=3.3.6 }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=3.4.5 }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=3.5.2 }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=3.6-dev }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=pypy2-5.6.0 }
    - { os: linux, dist: trusty, sudo: false, env: UBUNTU=14.04 PYENV=pypy3.3-5.5-alpha }

#    - { os: osx, osx_image: xcode6.4, language: generic, env: OSX=10.10 }
#    - { os: osx, osx_image: xcode7, language: generic, env: OSX=10.11 }
#    - { os: osx, osx_image: xcode8.2, language: generic, env: OSX=10.12 }

install:
  # Always use latest pyenv
  - git clone --depth=1 --branch=master https://github.com/yyuu/pyenv.git ~/.pyenv
  - export PATH="$HOME/.pyenv/bin:$PATH"
  - pyenv --version
  - pyenv install $PYENV
  - pyenv global $PYENV
  - pyenv rehash
  - python --version
  - pip --version
  - pip install virtualenv
  - python -m virtualenv ~/.venv
  - source ~/.venv/bin/activate
  - type brew || echo ERR
  - brew --version || echo ERR
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo OSX_IF_OP ; fi
  #- [[ "$TRAVIS_OS_NAME" == "osx" ]] && echo OSX_AND_OP
  - pip install pywinrm  # Just to test basic installation
  - pip install pywinrm[kerberos]
  - pip install pywinrm[credssp]
#  - pip install -r requirements-test.txt
script:
  - echo done
#  - py.test -v --pep8 --cov=winrm --cov-report=term-missing winrm/tests/

#after_success:
#  - coveralls
